federated token change

diff --git a/.github/workflows/deploy-pull-request.yaml b/.github/workflows/deploy-pull-request.yaml
--- a/.github/workflows/deploy-pull-request.yaml
+++ b/.github/workflows/deploy-pull-request.yaml
@@ -46,7 +46,8 @@ jobs:
   set-up-test-env:
     name: Create test env
     runs-on: ubuntu-latest
-
+    outputs:
+      token_creation_status: ${{ steps.OIDCTOKEN.status }}
     steps:
     - name: 'Az CLI login using OIDC'
       uses: azure/login@v1
@@ -56,6 +57,7 @@ jobs:
           subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
 
     - name: Create Azure OIDC Federated Token for Temporary PR ENV in App Registartion
+      id: OIDCTOKEN
       run: | 
         az ad app federated-credential create --id 0636d7e0-ff77-459e-ae19-4bce311b1df9 --parameters \
         "{\"name\":\"$SLOT_NAME\",
@@ -64,11 +66,16 @@ jobs:
         \"description\":\"TempToken for $SLOT_NAME\",
         \"audiences\": [ \"api://AzureADTokenExchange\" ]
         }" 
+      continue-on-error: true
 
-
-
+    # - name: Check on failures
+    #   if: set-up-test-env.steps.OIDCTOKEN.status == failure() || job.steps.world.status == failure()
+    #   run: exit 1
     - name: Create slot on staging site
       run: az webapp deployment slot create --resource-group $RESOURCE_GROUP  --name $WEBAPP_NAME --slot $SLOT_NAME
+
+    
+
 
   deploy:
     name: Deploy to test env
