main pr action

diff --git a/.github/workflows/deploy-pull-request.yaml b/.github/workflows/deploy-pull-request.yaml
--- a/.github/workflows/deploy-pull-request.yaml
+++ b/.github/workflows/deploy-pull-request.yaml
@@ -7,14 +7,17 @@ on:
 
 concurrency: ci-${{ github.event.number }}
 permissions:
-  id-token: write
-  contents: read
+    pull-requests: write
+    id-token: write
+    contents: read
 
 env:
   WEBAPP_NAME: apitestcole2
   RESOURCE_GROUP: appsvc_linux_centralus_basic
-  SLOT_NAME: pr-${{ github.event.number }}
+  SLOT_NAME: pr-${{ github.event.pull_request.title }}
   AZURE_WEBAPP_PACKAGE_PATH: '.'
+  GITHUB_TEMP_ENV: '${{ github.event.number }}'
+  GITHUB_PR_TITLE: ${{ github.event.pull_request.title }}
 
 jobs:
   build:
@@ -44,57 +47,30 @@ jobs:
   set-up-test-env:
     name: Create test env
     runs-on: ubuntu-latest
-
+    outputs:
+      token_creation_status: ${{ steps.OIDCTOKEN.status }}
     steps:
-    - name: Log into Azure CLI with service principal
-      uses: azure/login@v1.1
+    - name: 'Az CLI login using OIDC'
+      uses: azure/login@v1
       with:
           client-id: ${{ secrets.AZURE_CLIENT_ID }}
           tenant-id: ${{ secrets.AZURE_TENANT_ID }}
           subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
 
+    - name: Create Azure OIDC Federated Token for Temporary PR ENV in App Registartion
+      id: OIDCTOKEN
+      run: | 
+        az ad app federated-credential create --id 0636d7e0-ff77-459e-ae19-4bce311b1df9 --parameters \
+        "{\"name\":\"PR-$GITHUB_PR_TITLE\",
+        \"issuer\":\"https://token.actions.githubusercontent.com\",
+        \"subject\":\"repo:Trackonomy/env-protection-github:environment:PR-$GITHUB_PR_TITLE\",
+        \"description\":\"TempToken for $SLOT_NAME\",
+        \"audiences\": [ \"api://AzureADTokenExchange\" ]
+        }" 
+      continue-on-error: true
+
+    # - name: Check on failures
+    #   if: set-up-test-env.steps.OIDCTOKEN.status == failure() || job.steps.world.status == failure()
+    #   run: exit 1
     - name: Create slot on staging site
       run: az webapp deployment slot create --resource-group $RESOURCE_GROUP  --name $WEBAPP_NAME --slot $SLOT_NAME
-
-  deploy:
-    name: Deploy to test env
-    runs-on: ubuntu-latest
-    needs: [build, set-up-test-env]
-    environment:
-      name: "PR #${{ github.event.number }}"
-      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
-    permissions:
-      pull-requests: write
-
-    steps:
-    - name: Download artifact from build job
-      uses: actions/download-artifact@v2
-      with:
-        name: gettapevents-server
-
-    - name: Log into Azure CLI with service principal
-      uses: azure/login@v1.1
-      with:
-          client-id: ${{ secrets.AZURE_CLIENT_ID }}
-          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
-          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
-    
-    - name: Deploy to slot on staging site
-      uses: azure/webapps-deploy@v1
-      id: deploy-to-webapp
-      with: 
-        app-name: ${{ env.WEBAPP_NAME }}
-        slot-name:  ${{ env.SLOT_NAME }}
-        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
-    
-    - name: Comment on PR with the preview link
-      uses: mshick/add-pr-comment@v1
-      with:
-        message: |
-          ## Preview link: https://${{ env.WEBAPP_NAME }}-${{env.SLOT_NAME }}.azurewebsites.net 
-          
-          - Your changes have been deployed to the preview site. The preview site will update as you add more commits to this branch.
-          - The preview link is shareable, but will be deleted when the pull request is merged or closed.
-          > *This is an automated message.*
-        repo-token: ${{ secrets.GITHUB_TOKEN }}
-        repo-token-user-login: 'github-actions[bot]'
